### ISSUE TITLE
No matching distribution found for tensorflow==2.5.0

### ISSUE THREAD

**Issue by RidhamKaria** [WSU-SEAL/ToxiCR#3]
Hello,
I'm trying to install all the required package using below command 
`$pip install -r requirements.txt`
All packages are installed correctly except tensorflow. It throws below error.

```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.0 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0)

ERROR: No matching distribution found for tensorflow==2.5.0
```

Platform: PopOs-Ubuntu
Python: 3.10.6
pip: 23.0.1

Please let me know your views for this particular issue.

**Comment by jaydebsarker** [comment]
![issues_tensorflow](https://user-images.githubusercontent.com/11927430/229212280-00c68889-5f4b-4778-ac3e-9052436ed63d.PNG)

I rechecked it and it worked properly. I used python: 3.8.0. 
You can check that. Also, I used ubuntu OS for this.

**Comment by RidhamKaria** [comment]
@jaydebsarker thanks for the help. Now project works fine.
