### ISSUE TITLE
Regarding the pretrained model

### ISSUE THREAD

**Issue by umarIft** [WSU-SEAL/ToxiCR#4]
Hi,

Thank you for sharing the ToxiCR tool and the paper.

The pretrained model google drive link that is shared is not working. Is it possible that you can reshare the same in some way. Also, I have been running the BERT pretraining using ToxiCR in python and it takes a while to train a model. However, I am not sure if the trained model is saved anywhere because it will attempt to train the next time I run the same code. Please let me know what can be done in this regard. Thanks!

**Comment by aloussase** [comment]
Hi, I am also wondering about this.

**Comment by jaydebsarker** [comment]
Hi, the trained weight (.h5) is large (~1.3 GB). For that reason, it consumes a significant space from the google drive. 
In our readme file, all the descriptions are added on how to retrain and save the model. For your convenience, I have added it here again:

Retrain mode: to retrain the best performing BERT model (with keyword preprocessing):
$ python ToxiCR.py --algo BERT --embed bert --keyword --mode pretrain
The above command will save the best-performing model on the 'pre-trained' folder. 


Further, you can use the following to test your data. 

Test Mode: $ python ToxiCRTest.py

Let me know whether you are able to do it or not. Thanks for using our tool.

**Comment by aloussase** [comment]
Hi thanks for the reply. My team doesnt have access to a high end pc, do you think it is feasable to train the model on a laptop?

**Comment by jaydebsarker** [comment]
You can train it on laptop but should have GPU on that. You can train it on CPU but will take long time (~10 hours). 

We used 24 GB titan gpu that took 1 hr to train the full model.

**Comment by aloussase** [comment]
The machine I have at disposition to perform the training is very old. I get an "Illegal Instruction" error when training it with the current tensorflow version. Do you think I can use an older version of Python?

**Comment by jaydebsarker** [comment]
Look at readme.md file. 
#install all the requirements by following command:
$ pip install -r "requirements.txt"

Python version 3.8 would be fine for this model.

**Comment by aloussase** [comment]
I tried training the model on an AWS EC2 instance with GPU support and 16GB RAM but it seems that the OS kills the process due to high memory usage after the first epoch:

![image](https://github.com/WSU-SEAL/ToxiCR/assets/84427521/8453854b-245d-42db-8088-f74a4f2347d4)

I think we won't be able to use this without the pre-trained model.

**Comment by jaydebsarker** [comment]
Hi, 
I made available our best pre-trained model here:

https://drive.google.com/drive/folders/1hOn9hOmp7kja8Jig7qILwnSj4MvPgumN

Download it from here and run ToxiCRTest.py. 
Let me know whether you are okay or not.

**Comment by aloussase** [comment]
Hi thank you very much! I was able to use that pre-trained model succesfully.
 
I made a PR updating the tests to use that model's parameters and some formatting issues
in the main README if you are interested in that.

Thank you again for your work on this project!

**Comment by jaydebsarker** [comment]
Merged. Thank you.
